# ################################
# Model: Convolutional + GRU (decoder)
# Authors: Loren Lugosch & Mirco Ravanelli & Artem Ploujnikov 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data paths
output_folder: !ref results/RNN/<seed>
data_folder: /localscratch/librig2p
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
use_tensorboard: True
tensorboard_logs: !ref <output_folder>/logs/


input_lexicon: !ref <save_folder>/lexicon.csv
oov: !ref <save_folder>/oov.csv
pretrained_path: !ref <save_folder>/pretrained


# These three files are created from lexicon.csv.
build_lexicon: false
data_load: !name:speechbrain.dataio.dataset.DynamicItemDataset.from_json
lexicon_train_data: !ref <data_folder>/lexicon_train.json
lexicon_valid_data: !ref <data_folder>/lexicon_valid.json
lexicon_test_data: !ref <data_folder>/lexicon_test.json
sentence_train_data: !ref <data_folder>/sentence_train.json
sentence_valid_data: !ref <data_folder>/sentence_valid.json
sentence_test_data: !ref <data_folder>/sentence_test.json

skip_prep: False
sorting: random #ascending
origins: "*"
graphemes_space_separated: False
phonemes_space_separated: False
phonemes_enable_space: True
phonemes_count: 43

# Neural Parameters
lexicon_epochs: 50
lexicon_ctc_epochs: 10
sentence_epochs: 50
sentence_ctc_epochs: 10
lexicon_batch_size: 1024
sentence_batch_size: 64
ctc_weight: 0.5
lr: 0.002
save_for_pretrained: true

# Model parameters
output_neurons: !ref <phonemes_count>
enc_neurons: 512
dec_dropout: 0.5
dec_neurons: 512
dec_att_neurons: 256
dec_num_layers: 3
embedding_dim: 512

# Convolutional encoder parameters
enc_dilation: 1

# Special Token information
bos_index: 0
eos_index: 1
blank_index: 2

# Language Model
lm_emb_dim: 256 # dimension of the embeddings
lm_rnn_size: 512 # dimension of hidden layers
lm_layers: 2 # number of hidden layers
lm_output_neurons: !ref <phonemes_count>


# Beam Searcher
use_language_model: False
beam_search_min_decode_ratio: 0
beam_search_max_decode_ratio: 1.0
beam_search_beam_size: 16
beam_search_eos_threshold: 10.0
beam_search_using_max_attn_shift: False
beam_search_max_attn_shift: 10
beam_search_coverage_penalty: 5.0
beam_search_lm_weight: 0.5
beam_search_ctc_weight_decode: 0.4
beam_search_temperature: 1.25
beam_search_temperature_lm: 1.0

# Evaluation parameters
eval_dataset: train
eval_train_step: sentence
eval_batch_size: 256
eval_batch_count: 1
eval_reporting: raw
eval_mode: sentence
eval_prediction_sample_size: 10
eval_output_wer_file: false
eval_wer_file: !ref <save_folder>/wer_eval.txt


select_n_sentences: None

graphemes:
  - A
  - B
  - C
  - D
  - E
  - F
  - G
  - H
  - I
  - J
  - K
  - L
  - M
  - N
  - O
  - P
  - Q
  - R
  - S
  - T
  - U
  - V
  - W
  - X
  - Y
  - Z
  - "'"
  - " "

phonemes:
  - AA
  - AE
  - AH
  - AO
  - AW
  - AY
  - B
  - CH
  - D
  - DH
  - EH
  - ER
  - EY
  - F
  - G
  - HH
  - IH
  - IY
  - JH
  - K
  - L
  - M
  - N
  - NG
  - OW
  - OY
  - P
  - R
  - S
  - SH
  - T
  - TH
  - UH
  - UW
  - V
  - W
  - Y
  - Z
  - ZH


# Models
enc: !new:speechbrain.lobes.models.g2p.conv.Encoder
    input_shape: [null, null, !ref <embedding_dim>]
    conv_layers:
    - !new:speechbrain.nnet.CNN.Conv1d
      in_channels: !ref <embedding_dim>
      kernel_size: 3
      out_channels: 64
      dilation: !ref <enc_dilation>
      stride: 1
      padding: same
    - !new:speechbrain.lobes.models.g2p.conv.ResidualConvBlock &residual_conv
      in_channels: 64
      out_channels: 64
      kernel_size: 3
      stride: 1
      padding: same
    - !new:speechbrain.lobes.models.g2p.conv.ResidualConvBlock
      <<: *residual_conv
      in_channels: 64
      out_channels: 128
    - !new:speechbrain.lobes.models.g2p.conv.ResidualConvBlock
      <<: *residual_conv
      in_channels: 128
      out_channels: 256
    - !new:speechbrain.lobes.models.g2p.conv.ResidualConvBlock
      <<: *residual_conv
      in_channels: 256
      out_channels: 512


lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>  # 39 phonemes + 1 eos
    bias: False

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <enc_neurons>
    n_neurons: !ref <output_neurons>

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

encoder_emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: 28  # 27 chars + 1 bos
    embedding_dim: !ref <embedding_dim>

emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>  # 39 phonemes + 1 bos
    embedding_dim: !ref <embedding_dim>

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: !ref <enc_neurons>
    input_size: !ref <embedding_dim>
    rnn_type: lstm
    attn_type: content
    dropout: !ref <dec_dropout>
    hidden_size: !ref <dec_neurons>
    attn_dim: !ref <dec_att_neurons>
    num_layers: !ref <dec_num_layers>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

modules:
    model: !ref <model>
    enc: !ref <enc>
    encoder_emb: !ref <encoder_emb>
    emb: !ref <emb>
    dec: !ref <dec>
    lin: !ref <lin>
    ctc_lin: !ref <ctc_lin>
    out: !ref <log_softmax>

model: !new:speechbrain.lobes.models.g2p.model.AttentionSeq2Seq
    enc: !ref <enc>
    encoder_emb: !ref <encoder_emb>
    emb: !ref <emb>
    dec: !ref <dec>
    lin: !ref <lin>
    out: !ref <log_softmax>

lm_model: !new:speechbrain.lobes.models.RNNLM.RNNLM
    embedding_dim: !ref <lm_emb_dim>
    rnn_layers: !ref <lm_layers>
    rnn_neurons: !ref <lm_rnn_size>
    output_neurons: !ref <lm_output_neurons>
    return_hidden: true

opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <lin>
    ctc_linear: !ref <ctc_lin>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <beam_search_min_decode_ratio>
    max_decode_ratio: !ref <beam_search_max_decode_ratio>
    beam_size: !ref <beam_search_beam_size>
    eos_threshold: !ref <beam_search_eos_threshold>
    using_max_attn_shift: !ref <beam_search_using_max_attn_shift>
    max_attn_shift: !ref <beam_search_max_attn_shift>
    coverage_penalty: !ref <beam_search_coverage_penalty>


beam_searcher_lm: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearchLM
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <lin>
    ctc_linear: !ref <ctc_lin>
    language_model: !ref <lm_model>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    min_decode_ratio: !ref <beam_search_min_decode_ratio>
    max_decode_ratio: !ref <beam_search_max_decode_ratio>
    beam_size: !ref <beam_search_beam_size>
    eos_threshold: !ref <beam_search_eos_threshold>
    using_max_attn_shift: !ref <beam_search_using_max_attn_shift>
    max_attn_shift: !ref <beam_search_max_attn_shift>
    coverage_penalty: !ref <beam_search_coverage_penalty>
    ctc_weight: !ref <beam_search_ctc_weight_decode>
    lm_weight: !ref <beam_search_lm_weight>
    temperature: !ref <beam_search_temperature>
    temperature_lm: !ref <beam_search_temperature_lm>


lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0
    annealing_factor: 0.8
    patient: 0

seq_cost: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1

seq_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.nll_loss
        label_smoothing: 0.1
        reduction: batch

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats


lexicon_epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <lexicon_epochs>

sentence_epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <sentence_epochs>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        ctc_lin: !ref <ctc_lin>
        scheduler: !ref <lr_annealing>
        lexicon_counter: !ref <lexicon_epoch_counter>
        sentence_counter: !ref <sentence_epoch_counter>

model_output_keys:
    - p_seq
    - char_lens
    - encoder_out

grapheme_encoder: !new:speechbrain.dataio.encoder.TextEncoder
phoneme_encoder: !new:speechbrain.dataio.encoder.TextEncoder

encode_pipeline:
    batch: false
    use_padded_data: true
    output_keys:
        - grapheme_list
        - grapheme_encoded_list
        - grapheme_encoded
    steps:
        - !apply:speechbrain.lobes.models.g2p.attnrnn.clean_pipeline
          graphemes: !ref <graphemes>
        - !apply:speechbrain.lobes.models.g2p.attnrnn.grapheme_pipeline
          takes: txt_cleaned
          graphemes: !ref <graphemes>
          grapheme_encoder: !ref <grapheme_encoder>

decode_pipeline:
    batch: true
    output_keys:
        - phonemes
    steps:
        - !apply:speechbrain.lobes.models.g2p.attnrnn.beam_search_pipeline
          beam_searcher: !ref <beam_searcher>
        - !apply:speechbrain.lobes.models.g2p.attnrnn.phoneme_decoder_pipeline
          phoneme_encoder: !ref <phoneme_encoder>
          phonemes: !ref <phonemes>
          bos_index: !ref <bos_index>
          eos_index: !ref <eos_index>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  loadables:
    model: !ref <model>
  paths:
    model: !ref <pretrained_path>/model.ckpt

train_steps:
  - name: lexicon
    train_data: !ref <lexicon_train_data>
    valid_data: !ref <lexicon_valid_data>
    test_data: !ref <lexicon_test_data>
    epoch_counter: !ref <lexicon_epoch_counter>
    ctc_epochs: !ref <lexicon_ctc_epochs>
    wer_file: !ref <save_folder>/wer_lexicon.txt
    dataloader_opts:
        batch_size: !ref <lexicon_batch_size>

  - name: sentence
    train_data: !ref <sentence_train_data>
    valid_data: !ref <sentence_valid_data>
    test_data: !ref <sentence_test_data>
    epoch_counter: !ref <sentence_epoch_counter>
    ctc_epochs: !ref <sentence_ctc_epochs>
    wer_file: !ref <save_folder>/wer_sentence.txt
    dataloader_opts:
        batch_size: !ref <sentence_batch_size>

deps_pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        lm: !ref <lm_model>
    paths:
        lm: !ref <pretrained_path>/lm.ckpt
